module.exports = {
  event: 'follow',
  source: {
    id: 927482740009766900,
    id_str: '927482740009766912',
    name: 'Schokotron',
    screen_name: 'schokotron',
    location: null,
    url: null,
    description: null,
    protected: false,
    followers_count: 1,
    friends_count: 0,
    listed_count: 0,
    created_at: 'Mon Nov 06 10:28:11 +0000 2017',
    favourites_count: 0,
    utc_offset: -28800,
    time_zone: 'Pacific Time (US & Canada)',
    geo_enabled: false,
    verified: false,
    statuses_count: 0,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: null,
    profile_background_image_url_https: null,
    profile_background_tile: false,
    profile_image_url:
      'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
    profile_image_url_https:
      'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
    profile_link_color: '1DA1F2',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    default_profile: true,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    translator_type: 'none',
  },
  target: {
    id: 21404735,
    id_str: '21404735',
    name: 'David Beermann',
    screen_name: 'davidbeermann',
    location: 'Hamburg, Germany',
    url: 'http://t.co/yPtSGqxlNH',
    description: 'Interaction Design & Digital Media Art',
    protected: false,
    followers_count: 64,
    friends_count: 138,
    listed_count: 1,
    created_at: 'Fri Feb 20 15:25:04 +0000 2009',
    favourites_count: 47,
    utc_offset: 3600,
    time_zone: 'Bern',
    geo_enabled: true,
    verified: false,
    statuses_count: 188,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: '1A1B1F',
    profile_background_image_url:
      'http://pbs.twimg.com/profile_background_images/824545221/5396d67c04f57687cd009fe968d3ef90.png',
    profile_background_image_url_https:
      'https://pbs.twimg.com/profile_background_images/824545221/5396d67c04f57687cd009fe968d3ef90.png',
    profile_background_tile: true,
    profile_image_url:
      'http://pbs.twimg.com/profile_images/740571817719500800/vE-UT7Hq_normal.jpg',
    profile_image_url_https:
      'https://pbs.twimg.com/profile_images/740571817719500800/vE-UT7Hq_normal.jpg',
    profile_banner_url: 'https://pbs.twimg.com/profile_banners/21404735/1390868059',
    profile_link_color: '666666',
    profile_sidebar_border_color: '181A1E',
    profile_sidebar_fill_color: '252429',
    profile_text_color: '2FC2EF',
    profile_use_background_image: true,
    default_profile: false,
    default_profile_image: false,
    following: null,
    follow_request_sent: null,
    notifications: null,
    translator_type: 'none',
  },
  created_at: 'Sun Nov 26 17:51:10 +0000 2017',
}
